name: fmt

on:
  push:
    paths:
      - ".github/workflows/fmt.yml"
  schedule:
    - cron: "0 9 * * *"

jobs:
  fmt:
    name: fmt
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_version: 1.0.9
          terraform_wrapper: false

      - name: format
        id: fmt
        run: terraform fmt -recursive

      - uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: 🤖 terraform fmt -recursive
